[codechain]
quiet = false
base_path = "."
chain = "mainnet"

[mining]
mem_pool_mem_limit = 512 # MB
mem_pool_size = 524288
self_nomination_enable =false
mem_pool_fee_bump_shift = 3 # 12.5%
allow_create_shard = false
reseal_on_txs = "all"
reseal_min_period = 4000
no_reseal_timer = false
allowed_past_gap = 30000
allowed_future_gap = 5000

[network]
disable = false
interface = "0.0.0.0"
port = 3485
max_peers = 30
min_peers = 10
bootstrap_addresses = []
sync = true
transaction_relay = true
discovery = true
discovery_type = "unstructured"
discovery_refresh = 60000
discovery_bucket_size = 10
# whitelist_path = "whitelist.txt"
# blacklist_path = "blacklist.txt"

[rpc]
disable = false
interface = "127.0.0.1"
port = 8080

[ipc]
disable = false
path = "/tmp/jsonrpc.ipc"

[informer]
disable = true
interface = "127.0.0.1"
port = 7070
max_connections = 100

[ws]
disable = true
interface = "127.0.0.1"
port = 8081
max_connections = 100

[snapshot]
disable = true
path = "snapshot"
expiration = 100000 # blocks. About a week

[email_alarm]
disable = true
