[codechain]
quiet = false
base_path = "."

[mining]
mem_pool_mem_limit = 512 # MB
mem_pool_size = 524288
self_nomination_enable =false
mem_pool_fee_bump_shift = 3 # 12.5%
allow_create_shard = false
reseal_on_txs = "all"
reseal_min_period = 4000
no_reseal_timer = false
allowed_past_gap = 30000
allowed_future_gap = 5000

[network]
disable = true

[rpc]
disable = false
interface = "127.0.0.1"
port = 18080

[ipc]
disable = true

[ws]
disable = true

[snapshot]
disable = true

[email_alarm]
disable = true
