[codechain]
quiet = false
base_path = "."
password_path = "./password.json"

[mining]
engine_signer = "bccqygjwzj8wupc9m7du9ccef4j6k2u3erjuv2w8pt0"
mem_pool_mem_limit = 512 # MB
mem_pool_size = 524288
self_nomination_enable =false
mem_pool_fee_bump_shift = 3 # 12.5%
allow_create_shard = false
reseal_on_txs = "all"
reseal_min_period = 4000
no_reseal_timer = false
allowed_past_gap = 30000
allowed_future_gap = 5000

[network]
disable = false
port = 13486

[rpc]
disable = false
interface = "127.0.0.1"
port = 18081

[ipc]
disable = true

[ws]
disable = true

[snapshot]
disable = true

[email_alarm]
disable = true
