[package]
name = "module_account"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[dependencies]
rand = "0.6.1"
rustc-hex = "1.0"
rustc-serialize = "0.3"
lazy_static = "1.2"
bech32 = "0.2.2"
codechain-crypto = { git = "https://github.com/CodeChain-io/rust-codechain-crypto.git", version = "0.2" }
never-type = "0.1.0"
parking_lot = "0.6.0"
rand_xorshift = "0.1.0"
rlp = { git = "https://github.com/CodeChain-io/rlp.git", version = "0.4" }
sodiumoxide = "0.2.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_cbor = "0.11.1"
coordinator = {package = "coordinator", path = "../../coordinator" }
primitives = { git = "https://github.com/CodeChain-io/rust-codechain-primitives.git", version = "0.4" }
log = "0.4.6"
libc = "0.2"
time = "0.1.34"
smallvec = "0.4"
tempdir = "0.3"
rlp_derive = { git = "https://github.com/CodeChain-io/rlp.git", version = "0.2" }
codechain_key = {package = "codechain-key", path = "../../key"}

[dev-dependencies]
serde_json = "1.0"
matches = "0.1"
