default-sandboxer = "single-process"

[modules]

[modules.module-account]
hash = "a010000000012345678901234567890123456789012345678901234567890123"

[modules.module-account.exports]
stateful.stateful = {}
tx-owner.tx-owner = {}
account-manager.account-manager = {}
get-account-and-seq.get-account-and-seq = {}
handle-graphql-request.handle-graphql-request = {}

[modules.module-account.init-config]
thread-pool-size = 16

[modules.module-account.tags]
previliged = true

[modules.module-staking]
hash = "a020000000012345678901234567890123456789012345678901234567890123"
genesis-config = ["0a6902c51384a15d1062cac3a4e62c8d0c2eb02b4de7fa0a304ce4f88ea482d0", "0473f782c3aec053c37fe2bccefa9298dcf8ae3dc2262ae540a14a580ff773e6", "2502d5e6210679a19e45f3c0f93257e7a327baaf5f403f5ca1ab2685a9e1724e", "e909f311fd115ee412edcfcde88cc507370101f7635a67b9cb45390f1ccb4b5e"]

[modules.module-staking.exports]
init-genesis.init-genesis = {}
init-chain.init-chain = {}
update-chain.update-chain = {}

[modules.module-staking.imports]
token-manager = "module-token/token-manager"

[modules.module-staking.init-config]
thread-pool-size = 16

[modules.module-staking.tags]
previliged = true

[modules.module-stamp]
hash = "a030000000012345678901234567890123456789012345678901234567890123"
genesis-config = {}

[modules.module-stamp.exports]
tx-owner.tx-owner = {}
get-account-and-seq.get-account-and-seq = {}
init-genesis.init-genesis = {}

[modules.module-stamp.imports]
account-manager = "module-account/account-manager"
token-manager = "module-token/token-manager"

[modules.module-stamp.init-config]
thread-pool-size = 16

[modules.module-stamp.tags]
previliged = true

[modules.module-token]
hash = "a040000000012345678901234567890123456789012345678901234567890123"

[modules.module-token.exports]
tx-owner.tx-owner = {}
stateful.stateful = {}
token-manager.token-manager = {}
handle-graphql-request.handle-graphql-request = {}
get-account-and-seq.get-account-and-seq = {}

[modules.module-token.imports]
account-manager = "module-account/account-manager"

[modules.module-token.init-config]
thread-pool-size = 16

[modules.module-token.tags]
previliged = true

[modules.module-sorting]
hash = "a050000000012345678901234567890123456789012345678901234567890123"
transactions = ["get-account-and-seq"]

[modules.module-sorting.exports]
tx-sorter.tx-sorter = {}

[modules.module-sorting.imports]
account-manager = "module-account/account-manager"

[modules.module-sorting.init-config]
thread-pool-size = 16

[modules.module-sorting.tags]
previliged = true

[modules.module-util]
hash = "a060000000012345678901234567890123456789012345678901234567890123"

[modules.module-util.exports]
handle-graphql-request.handle-graphql-request = {}

[host]

[host.engine.tendermint.params]
timeoutPropose = 1000
timeoutProposeDelta = 1000
timeoutPrevote = 1000
timeoutPrevoteDelta = 1000
timeoutPrecommit = 1000
timeoutPrecommitDelta = 1000
timeoutCommit = 1000

[transactions]
hello = "module-account"
stamp = "module-stamp"
token = "module-token"

[param-defaults]
hi = "Annyeong Haseyo"
