[codechain]
base_path = "."
password_path = "./password.json"

[mining]
mem_pool_mem_limit = 4 # MB
mem_pool_size = 32768
reseal_on_txs = "all"
reseal_min_period = 0
allowed_past_gap = 30000
allowed_future_gap = 5000
engine_signer = "rjmxg19kCmkCxROEoV0QYsrDpOYsjQwusCtN5_oKMEzk-I6kgtAtc0"

[network]
disable = false
interface = "0.0.0.0"
port = 3030
max_peers = 30
min_peers = 10
bootstrap_addresses = [
    "127.0.0.1:3031",
    "127.0.0.1:3032",
    "127.0.0.1:3033"
]
sync = true
transaction_relay = true
discovery = true
discovery_type = "unstructured"
discovery_refresh = 60000
discovery_bucket_size = 10
# whitelist_path = "whitelist.txt"
# blacklist_path = "blacklist.txt"

[graphql]
port = 4040

[rpc]
disable = true

[ipc]
disable = true

[informer]
disable = true

[ws]
disable = true

[snapshot]
disable = true

[email_alarm]
disable = true
