[package]
name = "fml-macro-core"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]

[dependencies]
syn = { version = "1.0.16", features = ["full", "extra-traits", "visit", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "0.1.4"
